[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.18.1"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
