import {
  AlertCircle,
  ArrowDown,
  ArrowUp,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  Copy,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Package,
  Plus,
  RefreshCw,
  Search,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type Icon as LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Package,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  help: HelpCircle,
  twitter: Twitter,
  check: Check,
  copy: Copy,
  sun: SunMedium,
  moon: Moon,
  alert: CircleAlert,
  search: Search,
  refresh: RefreshCw,
  chevronUpDown: ChevronsUpDown,
  x: X,
}
